### PR TITLE
Use props to hide files instead of .pp extension

### PR DESCRIPTION
**Pull request by gtbuchanan**
The workaround of using the .pp extension no longer works in MSBuild 17.2.1 when using `TargetFrameworks`. Builds fail with an error like this:

> error CS0122: 'NotNullIfNotNullAttribute' is inaccessible due to its protection level

or this (depending on the situation):

> error CS0246: The type or namespace name 'NotNullWhen' could not be found

Using the `Visible` MSBuild property makes the intent more clear anyway. The approach is adapted from [here](https://til.cazzulino.com/dotnet/nuget/hide-contentfiles-from-your-nuget-packages).

Related to https://github.com/manuelroemer/IsExternalInit/pull/14

### CODE REVIEW

**Comment by manuelroemer** [comment]
That looks absolutely fantastic, many many thanks @gtbuchanan!
I will do some local tests and then look into publishing a new version of the package if nothing else seems to break.
